### ISSUE TITLE
functional component and how it is work 

### ISSUE THREAD

**Issue by Yemisirach** [Yemisirach/Math-magicians#6]
### Functional component and how it is used.
**In this issue page, I explained how to use functional components in React and the changes we need to make when using them instead of class components. Functional components are simpler to define and don't have state or lifecycle methods. We can use hooks for state and lifecycle methods, access props directly or through distructuring, and use arrow functions for event handlers.

Although the implementation is already completed, I am seeking feedback and suggestions for improvement.
In other to use functional components we have to follow the below step;

- [ ] We need to create a functional component which that is created as.
- [ ] In other to use react features in the functional components we then need hooks. We have several hooks namely the useState,useEffect, useContext, useReducer etc. In other to use any of them, they must be imported. In my project, I use useState react hook.
- [ ] I started using the functional component by creating a state property and initializing it to either a number or a string.
- [ ] I also came out with a method capable of setting that state property value

#### Look at Link https://github.com/Yemisirach/Math-magicians/tree/Math-magicians-events

I would be grateful for any assistance you can provide. Thank you.

**Comment by youmari** [comment]
Hi @Yemisirach , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great commit messages
✔️ PRO PR
✔️ No linter error 

## Required Changes ♻️

- [ ] NIce using the hooks as expected however I got the following error please make sure to fix it in order to complete the requirements 
![Screenshot 2023-03-02 at 14 43 15](https://user-images.githubusercontent.com/61790587/222445698-8f72a0b5-4a8d-430b-a8a0-7162515dca23.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Yemisirach** [comment]
- [ ]  I fix it in order to complete the requirements

**Comment by andersonlebon** [comment]
## Hi @Yemisirach 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Yemisirach** [comment]
- [ ] Thank you for your incredible support.
